#ifndef GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_GLOBAL_H
#define GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_LIBRARY)
#  define GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // GREENBOXSOLUTIONQTZINTSHAREDLIBRARY_GLOBAL_H
