#ifndef GREENBOXSOLUTIONLOGGINGLIBRARY_GLOBAL_H
#define GREENBOXSOLUTIONLOGGINGLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GREENBOXSOLUTIONLOGGINGLIBRARY_LIBRARY)
#  define GREENBOXSOLUTIONLOGGINGLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define GREENBOXSOLUTIONLOGGINGLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // GREENBOXSOLUTIONLOGGINGLIBRARY_GLOBAL_H
