#ifndef GREENBOXSOLUTIONUSBDEVICELIBRARY_GLOBAL_H
#define GREENBOXSOLUTIONUSBDEVICELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GREENBOXSOLUTIONUSBDEVICELIBRARY_LIBRARY)
#  define GREENBOXSOLUTIONUSBDEVICELIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define GREENBOXSOLUTIONUSBDEVICELIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // GREENBOXSOLUTIONUSBDEVICELIBRARY_GLOBAL_H
